### ISSUE TITLE
Clojure class-path for deps.edn with mvn/repos unable to resolve artifacts

### ISSUE THREAD

**Issue by CambodianCoder** [rm-hull/nvd-clojure#103]
Running `clj -M:nvd` in a clojure repo that has alternative `mvn/repos` in the deps.edn causes the following exception to be thrown. 

Currently testing on version 1.7.0

```
Execution error (ExceptionInfo) at clojure.tools.deps.alpha.extensions.maven/get-artifact (maven.clj:153).
Could not find artifact org.clojure:clojure:jar:1.10.3 in releases
```

![image](https://user-images.githubusercontent.com/35553625/142063047-9b8e7284-eaf0-49e7-8f2c-6ace06b3ff71.png)
 
Maven priority rules for packages that are externally hosted in a repositories such as Nexus/JFrog should resolve correctly with the command `clj -M:nvd`. 

Note that running the lein version of nvd where alternate mvn/repos are defined in a project.clj succeeds.

**Comment by vemv** [comment]
Hi, thanks for the report!

Sounds like yet another thing that can be fixed by following https://github.com/rm-hull/nvd-clojure#avoiding-classpath-interference. The Clojure CLI should be able to generate a production-like classpath no matter what. 

Then one feeds said classpath to nvd-clojure; this way nvd-clojure doesn't have to know anything about maven repos.
