### ISSUE TITLE
Set failure threshold by confidence, not just severity?

### ISSUE THREAD

**Issue by xiongtx** [rm-hull/nvd-clojure#18]
The `:fail-threshold` option allows the user to configure the [CVSS score](https://nvd.nist.gov/vuln-metrics/cvss) for failure, which is about severity.

Could we also set it based on confidence? For a lot of CLJ libs, severity is high for some reason but confidence is low. I'd guess most of these are false positive.

![image](https://user-images.githubusercontent.com/1624090/35587300-3df1b3c6-05b2-11e8-989e-68e54240ee19.png)

**Comment by rm-hull** [comment]
maybe we could allow either `:fail-threshold 7` (to maintain backwards compatibility) and then something like:

```
:fail-threshold {
  :severity 6
  :confidence 12
}
```
or
```
:fail-threshold {
  :confidence 12
}
```
or
```
:fail-threshold {
  :severity 6
}
```
Would need to work out the semantics when both severity and confidence are present :
* both breached means fail, or
* either breached means fail

**Comment by xiongtx** [comment]
When there are multiple metrics, the thing to do is to combine them into a single metric. Many papers could be published by researching how best to do this 😆 .

**Comment by vemv** [comment]
Hi,

IDK how things where as of Jan 2018. Over the last couple years with lein-nvd the suppression file suffices, and does not demand excessive tweaking.

With every new release, the underlying `dependency-check-core` lib is more reliable i.e. it will emit fewer false positives.

Some handy resources:

https://github.com/rm-hull/nvd-clojure#configuration-options
https://github.com/rm-hull/nvd-clojure/blob/master/.github/example_nvd_suppressions.xml
https://jeremylong.github.io/DependencyCheck/general/suppression.html

This simpler approach means more safety for consumers (since we don't try to figure out a heuristic that might yield false negatives) and less maintenance burden for nvd-clojure.

Cheers - V
